### ISSUE TITLE
请问这个怎么使用阿？

### ISSUE THREAD

**Issue by goldclam** [learn-help/baidu-translate#1]
请问这个怎么使用阿？

**Comment by learn-help** [comment]
![236578](https://user-images.githubusercontent.com/53334669/81298389-4b91b580-90a7-11ea-8e7c-5f979d761350.png)
您安装附加组件后，工具栏会出现百度翻译的按钮，点击即可使用。
（注：网页翻译、划词翻译功能正在开发中）
